[changelog]
header = "# Changelog\n\nAll notable changes to this project are documented in this file.\n"
body = """
{% if version %}
## {{ version }} - {{ timestamp | date(format=\"%Y-%m-%d\") }}
{% else %}
## Unreleased
{% endif %}

{% for group, commits in commits | group_by(attribute=\"group\") %}
### {{ group }}
{% for commit in commits -%}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | trim }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
sort_commits = "oldest"
commit_parsers = [
  { message = "^chore\\(release\\):|^chore: release v", skip = true },
  { message = "^feat",      group = "ğŸš€ Features"      },
  { message = "^fix",       group = "ğŸ› Bug Fixes"      },
  { message = "^docs?",     group = "ğŸ“š Documentation"  },
  { message = "^perf",      group = "âš¡ Performance"    },
  { message = "^refactor",  group = "ğŸšœ Refactor"       },
  { message = "^test",      group = "ğŸ§ª Testing"        },
  { message = "^chore|^ci", group = "âš™ï¸ Miscellaneous" },
  { message = "^revert",    group = "â—€ï¸ Revert"         },
]
filter_commits = true
tag_pattern = "v[0-9].*"
