[changelog]
header = "# Changelog\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message }}\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
sort_commits = "oldest"
commit_parsers = [
  { message = "^feat",      group = "ğŸš€ Features"      },
  { message = "^fix",       group = "ğŸ› Bug Fixes"      },
  { message = "^doc",       group = "ğŸ“š Documentation"  },
  { message = "^perf",      group = "âš¡ Performance"    },
  { message = "^refactor",  group = "ğŸšœ Refactor"        },
  { message = "^test",      group = "ğŸ§ª Testing"        },
  { message = "^chore|^ci", group = "âš™ï¸ Miscellaneous" },
  { message = "^revert",    group = "â—€ï¸ Revert"         },
]
filter_commits = true
tag_pattern = "v[0-9].*"
